// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Sm2ed5JKOP9Ll9HjnLauaF0qQC-jQ1E',
    appId: '1:776847273722:web:3335a29dc68a35122ee343',
    messagingSenderId: '776847273722',
    projectId: 'aido-e4447',
    authDomain: 'aido-e4447.firebaseapp.com',
    storageBucket: 'aido-e4447.firebasestorage.app',
    measurementId: 'G-3GRBSGLKK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRm_I8tMWsVGdL05ENJSEyqBdv46COYOg',
    appId: '1:776847273722:android:c7a9d5167b4962862ee343',
    messagingSenderId: '776847273722',
    projectId: 'aido-e4447',
    storageBucket: 'aido-e4447.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZ7deyh3wcMBmD35Y5mBOvuZBsLgtaV0',
    appId: '1:776847273722:ios:0f5dd5ed0d93abcf2ee343',
    messagingSenderId: '776847273722',
    projectId: 'aido-e4447',
    storageBucket: 'aido-e4447.firebasestorage.app',
    iosBundleId: 'com.example.aido',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaZ7deyh3wcMBmD35Y5mBOvuZBsLgtaV0',
    appId: '1:776847273722:ios:0f5dd5ed0d93abcf2ee343',
    messagingSenderId: '776847273722',
    projectId: 'aido-e4447',
    storageBucket: 'aido-e4447.firebasestorage.app',
    iosBundleId: 'com.example.aido',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Sm2ed5JKOP9Ll9HjnLauaF0qQC-jQ1E',
    appId: '1:776847273722:web:60b7af85f0236b542ee343',
    messagingSenderId: '776847273722',
    projectId: 'aido-e4447',
    authDomain: 'aido-e4447.firebaseapp.com',
    storageBucket: 'aido-e4447.firebasestorage.app',
    measurementId: 'G-25LM1X6HE5',
  );

}